
# auto-generated by CloudBrew TerraformAdapter for tf-test-1757425102-0
resource "null_resource" "tf_test_1757425102_0" {
  provisioner "local-exec" {
    command = "echo 'created tf-test-1757425102-0'"
  }
}
