
# auto-generated by CloudBrew TerraformAdapter for tf-test-1757425734-0
resource "null_resource" "tf_test_1757425734_0" {
  provisioner "local-exec" {
    command = "echo 'created tf-test-1757425734-0'"
  }
}
