
# auto-generated by CloudBrew TerraformAdapter for tf-test-1757425513-0
resource "null_resource" "tf_test_1757425513_0" {
  provisioner "local-exec" {
    command = "echo 'created tf-test-1757425513-0'"
  }
}
