
# auto-generated by CloudBrew TerraformAdapter for tf-test-1757424883-0
resource "null_resource" "tf_test_1757424883_0" {
  provisioner "local-exec" {
    command = "echo 'created tf-test-1757424883-0'"
  }
}
