
# auto-generated by CloudBrew TerraformAdapter for tf-test-1757426079-0
resource "null_resource" "tf_test_1757426079_0" {
  provisioner "local-exec" {
    command = "echo 'created tf-test-1757426079-0'"
  }
}
