name: Pre-build
on: [pull_request, push]


jobs:
prebuild:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: Set up Python
uses: actions/setup-python@v4
with:
python-version: '3.11'
- name: Install dev deps
run: |
python -m pip install --upgrade pip
pip install -r ci/requirements-dev.txt
- name: Run prebuild (Makefile)
run: make prebuild